
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: machine-approver
rules:
- apiGroups:
  - "cluster.x-k8s.io"
  resources:
  - machines
  - machines/status
  verbs:
  - get
  - list
  - watch
